### ISSUE TITLE
FriTap on Android 13 does not work?

### ISSUE THREAD

**Issue by Aniketh01** [fkie-cad/friTap#7] opened 2023-02-22 12:08 UTC
Hi, 

I have been testing friTap on Pixel 6a with Android 13. The device is rooted using magisk. Although I'm able to capture "full_capture" as it is done via tcpdump, none of the plaintext traffic is being captured for some reason. 

Initial investigation made me realise that it is due to the fact that none of the "datalog" entries are being forwarded. `message["contentType"] = "datalog"`. Could this mean that the hooks on native SSL libraries does not work for Android 13?

**Comment by monkeywave** [comment] 2023-06-28 17:01
Just to clarify:
- `--full_capture` means full packet capture with tcpdump therefore no plaintext pcap. To decrypt it the keys from `-k <keylog>` can be used
- `-p <pcap>` means we will only get a plaintext pcap with the plaintext data from the identified TLS traffic. 

Depending on the app it still works on Android 13 although there are some apps where it doens't work on Android.

So it actually depends on the used app and its used TLS library :-)

Because I can't reproduce the issue in general I will close this issue. If you encounter this problem with different Android Apps on Android 13 I will have a look into this.

**Closed by monkeywave** 2023-06-28 17:01 UTC
